"""Guided interface verification on synthetic localhost:8001 only."""
from playwright.sync_api import sync_playwright,expect

BASE='http://127.0.0.1:8001'
with sync_playwright() as p:
    browser=p.chromium.launch()
    desktop=browser.new_context(viewport={'width':1440,'height':1100})
    page=desktop.new_page();errors=[];page.on('pageerror',lambda err:errors.append(str(err)))
    page.goto(BASE+'/admin')
    expect(page.locator('#login-form')).to_be_visible()
    expect(page.get_by_role('link',name='Créer mon compte')).to_be_visible()
    page.locator('[name=username]').fill('admin')
    page.locator('[name=password]').fill('browser-fixture-password-123456789')
    page.get_by_role('button',name='Se connecter').click()
    expect(page.locator('#home')).to_be_visible()
    expect(page.locator('.maison-intro')).to_contain_text('Vos voyageurs.')
    expect(page.locator('#mode')).to_have_text('TEST MODE')
    page.screenshot(path='/private/tmp/airbnb-manager-desktop.png',full_page=True)
    page.locator('[data-page=connections]').click()
    expect(page.locator('.connection-card')).to_have_count(3)
    expect(page.locator('#connections-content')).to_contain_text('Connecter mon compte Guesty')
    page.screenshot(path='/private/tmp/airbnb-manager-connections.png',full_page=True)
    page.locator('[data-page=properties]').click()
    expect(page.locator('#property-list .property-card').first).to_be_visible()
    assert page.locator('#property-list .property-card').count() >= 2
    page.locator('#property-list .property-card').filter(has_text='CAIRE1').click()
    expect(page.locator('#dialog-body')).not_to_contain_text('SYNTHETIC-A')
    expect(page.locator('#dialog-body')).to_contain_text('Photos, vidéos et guide')
    page.locator('[data-state=working]').click()
    expect(page.locator('dialog')).not_to_be_visible()
    # Optional forms stay available behind the property memory.
    page.locator('#property-list .property-card').filter(has_text='CAIRE1').click()
    page.locator('[data-wizard]').click()
    expect(page.locator('#onboard-form')).to_be_visible()
    # Skip unknown groups until the media question. This verifies durable deferral.
    for _ in range(15):
        if page.locator('[name="media:access_video"]').count():break
        page.locator('[data-wizard-defer]').click()
        page.wait_for_timeout(150)
    expect(page.locator('[name="media:access_video"]')).to_be_visible()
    page.locator('[name="media:access_video"]').select_option('true')
    expect(page.locator('.media-help').first).to_be_visible()
    for name in ['access_photos','arrival_guide']:
        if page.locator('[name="media:'+name+'"]').count():page.locator('[name="media:'+name+'"]').select_option('false')
    page.locator('#onboard-form button').click()
    expect(page.locator('#confirm-upload')).to_be_visible()
    expect(page.locator('#dialog-body')).to_contain_text('CAIRE1')
    page.locator('#confirm-upload').check()
    page.locator('#file-picker').set_input_files({'name':'synthetic-arrival.mp4','mimeType':'video/mp4','buffer':b'\x00\x00\x00\x18ftypmp42synthetic-video'})
    expect(page.locator('#onboard-form')).to_be_visible()
    page.locator('[data-property-overview]').click()
    expect(page.locator('#dialog-body')).to_contain_text('synthetic-arrival.mp4')
    expect(page.locator('[data-publish-media]')).to_be_visible()
    page.screenshot(path='/private/tmp/airbnb-manager-property.png',full_page=True)
    page.locator('#close-dialog').click()
    page.locator('[data-page=home]').click()
    page.locator('#home [data-open-page=feed]').click()
    page.locator('.original-inbox summary').click()
    expect(page.locator('.feed-card')).to_have_count(1)
    expect(page.locator('.received-card')).to_have_count(1)
    page.locator('.received-card').click()
    expect(page.locator('.thread-message')).to_contain_text('Can we check in at 1pm?')
    page.locator('[data-verify-identity]').click()
    expect(page.locator('#dialog-title')).to_have_text('Confirmer le bon logement')
    page.locator('[data-confirm-identity]').click()
    expect(page.locator('dialog')).not_to_be_visible()
    page.locator('[data-feedback-kind=correct]').click()
    page.locator('[name=corrected]').fill('Hi! I’ll do my best :) I’ll confirm as soon as possible.')
    page.get_by_role('button',name='Valider et enregistrer').click()
    expect(page.locator('.feedback-history')).to_contain_text('Correction humaine validée')
    page.locator('[data-page=alerts]').click()
    page.get_by_role('button',name='Accepter',exact=True).click()
    page.get_by_role('button',name='Préparer la réponse').click()
    page.locator('[data-confirm-decision][data-accept=true]').click()
    expect(page.locator('.alert-card')).to_have_count(0)
    page.locator('[data-page=settings]').click()
    page.locator('[data-set-mode=live]').click()
    expect(page.locator('dialog')).to_contain_text('ALLOW_LIVE_SENDS=false')
    page.locator('[data-confirm-mode][data-accept=true]').click()
    expect(page.locator('#mode')).to_have_text('LIVE')
    page.locator('[data-set-mode=test]').click()
    expect(page.locator('#mode')).to_have_text('TEST MODE')
    mobile=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True)
    mobile.add_cookies(desktop.cookies())
    mp=mobile.new_page();mp.on('pageerror',lambda err:errors.append(str(err)))
    mp.goto(BASE+'/admin')
    expect(mp.locator('.maison-intro')).to_be_visible()
    mp.screenshot(path='/private/tmp/airbnb-manager-mobile.png',full_page=True)
    assert mp.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile horizontal overflow'
    mp.locator('[data-page=connections]').click()
    expect(mp.locator('.connection-card')).to_have_count(3)
    assert mp.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Connections overflow'
    mp.screenshot(path='/private/tmp/airbnb-manager-mobile-connections.png',full_page=True)
    # Signup from the browser with independently chosen credentials and empty workspace.
    signup=browser.new_context(viewport={'width':1280,'height':1000})
    sp=signup.new_page();sp.on('pageerror',lambda err:errors.append(str(err)))
    sp.goto(BASE+'/admin/login');sp.get_by_role('link',name='Créer mon compte').click()
    expect(sp.locator('#register-form')).to_be_visible()
    sp.locator('[name=workspace_name]').fill('Nouvelle conciergerie fictive')
    sp.locator('[name=email]').fill('browser-'+__import__('uuid').uuid4().hex+'@example.com')
    sp.locator('[name=password]').fill('my-own-browser-password-123')
    sp.locator('[name=confirm_password]').fill('my-own-browser-password-123')
    sp.get_by_role('button',name='Créer mon compte').click()
    expect(sp.locator('#workspace-name')).to_have_text('Nouvelle conciergerie fictive')
    sp.locator('[data-page=properties]').click()
    expect(sp.locator('#property-list .property-card')).to_have_count(0)
    assert not errors,errors
    browser.close()
    print('Guided desktop/mobile verified: signup, independent workspace, agent home, connections, property memory, questions, yes->video upload->stored file, feedback, decisions, safe mode.')
