"""guesty inventory and property knowledge"""
from alembic import op
import sqlalchemy as sa
revision = '5fcbbed24089'
down_revision = 'cd3d82f04a71'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_knowledge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_reference', sa.String(length=160), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('knowledge_type', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.Float(), nullable=False),
    sa.Column('valid_until', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'property_id'], ['properties.organization_id', 'properties.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id'),
    sa.UniqueConstraint('organization_id', 'property_id', 'key', 'source')
    )
    op.create_index(op.f('ix_property_knowledge_property_id'), 'property_knowledge', ['property_id'], unique=False)
    op.create_table('property_sync',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('encrypted_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('synced_at', sa.Float(), nullable=False),
    sa.Column('missing_since', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'property_id'], ['properties.organization_id', 'properties.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'organization_id'),
    sa.UniqueConstraint('organization_id', 'external_id')
    )
    if op.get_bind().dialect.name=='postgresql':
        for table in ('property_knowledge','property_sync'):
            op.execute(sa.text(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY'))
            op.execute(sa.text(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY'))
            op.execute(sa.text(f"CREATE POLICY organization_isolation ON {table} USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))"))
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_sync')
    op.drop_index(op.f('ix_property_knowledge_property_id'), table_name='property_knowledge')
    op.drop_table('property_knowledge')
    # ### end Alembic commands ###
