"""initial_schema"""
from alembic import op
import sqlalchemy as sa
revision = 'a703e913333a'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sent_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_key', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=120), nullable=False),
    sa.Column('guesty_message_id', sa.String(length=120), nullable=True),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_key'),
    sa.UniqueConstraint('guesty_message_id')
    )
    op.create_index(op.f('ix_agent_sent_messages_conversation_id'), 'agent_sent_messages', ['conversation_id'], unique=False)
    op.create_table('incoming_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('message_key', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=120), nullable=True),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.Float(), nullable=False),
    sa.Column('due_at', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_key')
    )
    op.create_index(op.f('ix_incoming_events_conversation_id'), 'incoming_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_incoming_events_due_at'), 'incoming_events', ['due_at'], unique=False)
    op.create_index(op.f('ix_incoming_events_status'), 'incoming_events', ['status'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('retry_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('guesty_listing_id', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('check_in', sa.String(length=5), nullable=False),
    sa.Column('check_out', sa.String(length=5), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('onboarding_step', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guesty_listing_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('style_profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('profile', sa.Text(), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('manager', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('encrypted_change', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('guesty_conversation_id', sa.String(length=120), nullable=True),
    sa.Column('reservation_id', sa.String(length=120), nullable=True),
    sa.Column('guest_name', sa.String(length=160), nullable=False),
    sa.Column('encrypted_summary', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notification_status', sa.String(length=20), nullable=False),
    sa.Column('notification_attempts', sa.Integer(), nullable=False),
    sa.Column('notification_due', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_table('guesty_id_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'external_id')
    )
    op.create_table('manager_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('manager', sa.String(length=80), nullable=False),
    sa.Column('encrypted_action', sa.Text(), nullable=False),
    sa.Column('encrypted_old', sa.Text(), nullable=False),
    sa.Column('encrypted_new', sa.Text(), nullable=False),
    sa.Column('expected_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_access',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('property_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Float(), nullable=False),
    sa.Column('valid_until', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'key')
    )
    op.create_table('property_wifi',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_wifi')
    op.drop_table('property_states')
    op.drop_table('property_access')
    op.drop_table('manager_changes')
    op.drop_table('guesty_id_mappings')
    op.drop_table('escalations')
    op.drop_table('audit_logs')
    op.drop_table('style_profiles')
    op.drop_table('properties')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_incoming_events_status'), table_name='incoming_events')
    op.drop_index(op.f('ix_incoming_events_due_at'), table_name='incoming_events')
    op.drop_index(op.f('ix_incoming_events_conversation_id'), table_name='incoming_events')
    op.drop_table('incoming_events')
    op.drop_index(op.f('ix_agent_sent_messages_conversation_id'), table_name='agent_sent_messages')
    op.drop_table('agent_sent_messages')
    # ### end Alembic commands ###
