"""historical_listing_identity"""
from alembic import op
import sqlalchemy as sa
revision = 'cd3d82f04a71'
down_revision = '4ede41e41e55'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_lifecycle', sa.Column('canonical_listing_id', sa.String(length=120), nullable=True))
    bind=op.get_bind()
    for oid in bind.execute(sa.text("SELECT id FROM organizations")).scalars().all():
        if bind.dialect.name=="postgresql":bind.execute(sa.text("SELECT set_config('app.organization_id', :oid, true)"),{"oid":oid})
        bind.execute(sa.text("UPDATE listing_lifecycle SET canonical_listing_id=(SELECT guesty_listing_id FROM properties WHERE properties.id=listing_lifecycle.property_id AND properties.organization_id=listing_lifecycle.organization_id) WHERE organization_id=:oid AND source='migration:initial_inventory'"),{"oid":oid})
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_lifecycle', 'canonical_listing_id')
    # ### end Alembic commands ###
