"""workspace_agent_mode"""
from alembic import op
import sqlalchemy as sa
revision = 'dfd7068ed4bf'
down_revision = 'd448551f37ec'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_mode_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requested_mode', sa.String(length=10), nullable=False),
    sa.Column('expected_revision', sa.Integer(), nullable=False),
    sa.Column('proposed_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id')
    )
    op.add_column('organizations', sa.Column('agent_mode', sa.String(length=10), nullable=False, server_default='test'))
    op.add_column('organizations', sa.Column('mode_revision', sa.Integer(), nullable=False, server_default='1'))
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text('ALTER TABLE agent_mode_changes ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text('ALTER TABLE agent_mode_changes FORCE ROW LEVEL SECURITY'))
        op.execute(sa.text("CREATE POLICY organization_isolation ON agent_mode_changes USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))"))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'mode_revision')
    op.drop_column('organizations', 'agent_mode')
    op.drop_table('agent_mode_changes')
    # ### end Alembic commands ###
