"""listing_lifecycle_and_onboarding_progress"""
from alembic import op
import sqlalchemy as sa
import time
import uuid
revision = '4ede41e41e55'
down_revision = 'f43a4e2528c8'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_lifecycle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('from_billable', sa.Boolean(), nullable=False),
    sa.Column('to_billable', sa.Boolean(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'property_id'], ['properties.organization_id', 'properties.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id')
    )
    op.create_index(op.f('ix_listing_lifecycle_occurred_at'), 'listing_lifecycle', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_listing_lifecycle_property_id'), 'listing_lifecycle', ['property_id'], unique=False)
    op.add_column('properties', sa.Column('status', sa.String(length=20), nullable=False,server_default='onboarding'))
    op.add_column('properties', sa.Column('activated_at', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('deactivated_at', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('is_billable', sa.Boolean(), nullable=False,server_default=sa.false()))
    op.add_column('properties', sa.Column('onboarding_data', sa.JSON(), nullable=False,server_default='{}'))
    bind=op.get_bind();now=time.time()
    organizations=bind.execute(sa.text("SELECT id FROM organizations")).scalars().all()
    for oid in organizations:
        if bind.dialect.name=="postgresql":bind.execute(sa.text("SELECT set_config('app.organization_id', :oid, true)"),{"oid":oid})
        rows=bind.execute(sa.text("SELECT id,is_active,archived_at FROM properties WHERE organization_id=:oid"),{"oid":oid}).mappings().all()
        for row in rows:
            status='archived' if row['archived_at'] else 'active' if row['is_active'] else 'onboarding'
            bind.execute(sa.text("UPDATE properties SET status=:status,activated_at=:activation WHERE id=:pid AND organization_id=:oid"),{"status":status,"activation":now if status=='active' else None,"pid":row['id'],"oid":oid})
            bind.execute(sa.text("INSERT INTO listing_lifecycle (id,organization_id,property_id,from_status,to_status,from_billable,to_billable,actor,source,occurred_at) VALUES (:id,:oid,:pid,NULL,:status,false,false,'system','migration:initial_inventory',:now)"),{"id":str(uuid.uuid4()),"oid":oid,"pid":row['id'],"status":status,"now":now})
    if bind.dialect.name=="postgresql":
        op.execute(sa.text('ALTER TABLE listing_lifecycle ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text('ALTER TABLE listing_lifecycle FORCE ROW LEVEL SECURITY'))
        op.execute(sa.text("CREATE POLICY organization_isolation ON listing_lifecycle USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))"))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'onboarding_data')
    op.drop_column('properties', 'is_billable')
    op.drop_column('properties', 'deactivated_at')
    op.drop_column('properties', 'activated_at')
    op.drop_column('properties', 'status')
    op.drop_index(op.f('ix_listing_lifecycle_property_id'), table_name='listing_lifecycle')
    op.drop_index(op.f('ix_listing_lifecycle_occurred_at'), table_name='listing_lifecycle')
    op.drop_table('listing_lifecycle')
    # ### end Alembic commands ###
