"""test_feed_human_feedback_and_style"""
from alembic import op
import sqlalchemy as sa
revision = 'f43a4e2528c8'
down_revision = 'dfd7068ed4bf'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_style_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('human_user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_body', sa.Text(), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("source IN ('test_correction','manual_manager','guesty_human')", name='human_source_only'),
    sa.ForeignKeyConstraint(['human_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id'),
    sa.UniqueConstraint('organization_id', 'source', 'source_id')
    )
    op.create_table('style_preferences',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('learned_traits', sa.JSON(), nullable=False),
    sa.Column('explicit_traits', sa.JSON(), nullable=False),
    sa.Column('source_example_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id')
    )
    op.create_table('ai_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sent_message_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('reservation_id', sa.String(length=120), nullable=True),
    sa.Column('conversation_id', sa.String(length=120), nullable=False),
    sa.Column('guest_name', sa.String(length=160), nullable=False),
    sa.Column('encrypted_received', sa.Text(), nullable=False),
    sa.Column('encrypted_original', sa.Text(), nullable=False),
    sa.Column('encrypted_context', sa.Text(), nullable=False),
    sa.Column('encrypted_escalation', sa.Text(), nullable=False),
    sa.Column('situation', sa.String(length=50), nullable=False),
    sa.Column('effective_test', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'property_id'], ['properties.organization_id', 'properties.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'sent_message_id'], ['agent_sent_messages.organization_id', 'agent_sent_messages.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id'),
    sa.UniqueConstraint('organization_id', 'sent_message_id')
    )
    op.create_index(op.f('ix_ai_observations_conversation_id'), 'ai_observations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_observations_property_id'), 'ai_observations', ['property_id'], unique=False)
    op.create_table('response_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('human_user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('encrypted_received', sa.Text(), nullable=False),
    sa.Column('encrypted_original', sa.Text(), nullable=False),
    sa.Column('encrypted_corrected', sa.Text(), nullable=False),
    sa.Column('encrypted_reason', sa.Text(), nullable=False),
    sa.Column('situation', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['human_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'observation_id'], ['ai_observations.organization_id', 'ai_observations.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'property_id'], ['properties.organization_id', 'properties.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id')
    )
    op.create_index(op.f('ix_response_feedback_observation_id'), 'response_feedback', ['observation_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        for name in ["human_style_examples","style_preferences","ai_observations","response_feedback"]:
            op.execute(sa.text(f'ALTER TABLE "{name}" ENABLE ROW LEVEL SECURITY'))
            op.execute(sa.text(f'ALTER TABLE "{name}" FORCE ROW LEVEL SECURITY'))
            op.execute(sa.text(f"CREATE POLICY organization_isolation ON \"{name}\" USING (organization_id = current_setting('app.organization_id', true)) WITH CHECK (organization_id = current_setting('app.organization_id', true))"))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_feedback_observation_id'), table_name='response_feedback')
    op.drop_table('response_feedback')
    op.drop_index(op.f('ix_ai_observations_property_id'), table_name='ai_observations')
    op.drop_index(op.f('ix_ai_observations_conversation_id'), table_name='ai_observations')
    op.drop_table('ai_observations')
    op.drop_table('style_preferences')
    op.drop_table('human_style_examples')
    # ### end Alembic commands ###
